name: Build serverless-xhttp Image

on:
  push:
    branches: [ serverless-xhttp ]
    paths:
      - 'Dockerfile'
      - 'app.js'
      - 'package.json'
      - 'index.html'
  pull_request:
    branches: [ serverless-xhttp ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        # 移除 ref: huggingface，自动检出触发工作流的分支（serverless-xhttp）

      - name: 登录 GitHub 容器仓库
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 配置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/serverless-xhttp:latest
          labels:
            org.opencontainers.image.source: ${{ github.event.repository.html_url }}
            org.opencontainers.image.description: HTTP server for serverless-xhttp branch
            org.opencontainers.image.licenses: MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
