name: huggggg

on:
  push:
    branches: [ "serverless-xhttp" ]
    paths:
      - "Dockerfile"
      - "**/*.js"
      - "**/*.html"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout serverless-xhttp branch
        uses: actions/checkout@v4
        with:
          ref: "serverless-xhttp"
          fetch-depth: 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push serverless-xhttp image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/serverless-xhttp:latest
            ghcr.io/${{ github.repository_owner }}/serverless-xhttp:${{ github.sha }}
          labels:
            org.opencontainers.image.title: "serverless-xhttp Branch Image"
            org.opencontainers.image.version: ${{ github.sha }}
            org.opencontainers.image.source: ${{ github.event.repository.html_url }}
            org.opencontainers.image.branch: "serverless-xhttp"
            org.opencontainers.image.licenses: MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
