name: Build serverless-xhttp Image

on:
  push:
    branches: [ serverless-xhttp ]  # 仅监听 serverless-xhttp 分支
    paths:
      - 'Dockerfile'
      - 'app.js'
      - 'package.json'
      - 'index.html'
  pull_request:
    branches: [ serverless-xhttp ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          # 关键：不指定任何与 huggingface 相关的参数
          # 移除 ref: huggingface 或任何包含 huggingface 的过滤规则
          fetch-depth: 0  # 拉取完整历史，避免分支过滤问题

      - name: 登录 GitHub 容器仓库
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 配置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            # 镜像标签仅关联 serverless-xhttp
            ghcr.io/${{ github.repository_owner }}/tools:serverless-xhttp
          labels:
            org.opencontainers.image.source: ${{ github.event.repository.html_url }}
            org.opencontainers.image.description: 基于 serverless-xhttp 分支的镜像
            org.opencontainers.image.licenses: MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
