name: Build serverless-xhttp Image

# 仅监听 serverless-xhttp 分支的变动
on:
  push:
    branches: [ serverless-xhttp ]
    paths:  # 仅当这些文件变动时触发，减少不必要构建
      - 'Dockerfile'
      - 'app.js'
      - 'package.json'
      - 'index.html'
  pull_request:
    branches: [ serverless-xhttp ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 允许推送镜像到 GitHub Packages

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        # 不指定 ref，自动关联触发工作流的 serverless-xhttp 分支

      - name: 登录 GitHub 容器仓库
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动获取的临时令牌

      - name: 配置 Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true  # 确保安装最新 Buildx 组件，减少兼容性问题

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .  # 构建上下文为当前目录
          push: true  # 推送镜像到仓库
          tags: |
            # 镜像标签固定为分支名，明确对应 serverless-xhttp
            ghcr.io/${{ github.repository_owner }}/serverless-xhttp-image:latest
          labels:
            org.opencontainers.image.title: "serverless-xhttp Image"
            org.opencontainers.image.description: "镜像仅对应 serverless-xhttp 分支"
            org.opencontainers.image.source: ${{ github.event.repository.html_url }}
            org.opencontainers.image.licenses: MIT
          cache-from: type=gha  # 启用缓存加速构建
          cache-to: type=gha,mode=max
          # 错误处理：构建失败时自动重试一次
          retry: 1
